name: chess_ai
services:
  api:
    build: ./api
    ports:
     - "3001:8080"
  client:
    build: ./client
    ports:
     - "3000:5175"
  database:
    image: mongodb/mongodb-community-server:6.0-ubi8
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=r00t
    ports:
      - "27018:27017"