# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore

      - name: Test
        run: dotnet test -c Release --no-build --verbosity normal

      - name: Archive build artifacts
        run: cd /home/runner/work/Personal_Website/Personal_Website/api/bin/Release/ && tar -czvf API.tar.gz net8.0

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: /home/runner/work/Personal_Website/Personal_Website/api/bin/Release/API.tar.gz
