# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore

      - name: Test
        run: dotnet test -c Release --no-build --verbosity normal

      - name: Archive build artifacts
        run: cd /home/runner/work/Personal_Website/Personal_Website/api/bin/Release/ && tar -czvf API.tar.gz net8.0

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: /home/runner/work/Personal_Website/Personal_Website/api/bin/Release/API.tar.gz

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download package
        uses: actions/download-artifact@v4
        with:
          name: package

      - name: Display files in working directory
        run: ls

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{secrets.API_KEY}}
          known_hosts: unnecessary

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{secrets.API_HOST}}  >> ~/.ssh/known_hosts

      - name: Transfer build artifacts to DO Droplet
        uses: appleboy/scp-action@master
        with:
          host: ${{secrets.API_HOST}}
          username: ${{secrets.API_USERNAME}}
          key: ${{secrets.API_KEY}}
          source: API.tar.gz
          target: /var/www/temp/

      - name: Deploy application
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.API_HOST}}
          username: ${{secrets.API_USERNAME}}
          key: ${{secrets.API_KEY}}
          script: |
            sudo systemctl stop api.service
            cd ..
            cd /var/www/
            rm -rf api.parker-stovall.com
            mkdir api.parker-stovall.com
            cd /var/www/temp/
            tar -xvf API.tar.gz -C /var/www/api.parker-stovall.com
            cd /var/www/api.parker-stovall.com/
            mv net8.0/* .
            sudo systemctl restart api.service
            cd /var/www/temp/
            rm -rf API.tar.gz
