name: React PR

on:
  pull_request:
    branches: ['master']

jobs:
  Build_React:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client/
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Lint and build
        run: |
          npm run lint
          npm run build

  Build_DotNet:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore

      - name: Test
        run: dotnet test -c Release --no-build --verbosity normal

  Run_Playwright_Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: 'npm'
      - name: Run docker-compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: './Docker/MongoDB.yml'
      - name: Install Client dependencies
        run: |
          cd client
          npm ci
      - name: Install API dependencies
        run: |
          cd api
          dotnet restore
          dotnet build
      - name: Run Playwright tests
        run: |
          cd playwright_testing
          npx playwright test
