name: Pull Request - Build and Test

on:
  pull_request:

jobs:
  Build_And_Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: "npm"

      - name: Install Client dependencies
        run: |
          cd client
          npm ci
          npm run lint
          npm run build

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: ./api/global.json

      - name: Install API dependencies
        run: |
          cd api
          dotnet restore
          dotnet tool restore
          dotnet build

      - name: Install Playwright dependencies
        run: |
          cd playwright_tests
          npm ci
          npx playwright install chromium --with-deps

      - name: Run Playwright tests
        run: |
          mkdir -m 777 Docker/data
          cd playwright_tests
          npx playwright test

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
