name: React

on:
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client/
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm install
      - run: npm run build
      - run: rm -rf node_modules

      - name: Archive build artifacts
        run: cd /home/runner/work/Personal_Website/Personal_Website/ && tar -czvf client.tar.gz client

      - name: Upload build artifacts for deployment
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: /home/runner/work/Personal_Website/Personal_Website/client.tar.gz
