name: React
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client/
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm install
      - run: npm run build
      - run: rm -rf node_modules

      - name: Archive build artifacts
        run: cd /home/runner/work/Personal_Website/Personal_Website/ && tar -czvf client.tar.gz client

      - name: Upload build artifacts for deployment
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: /home/runner/work/Personal_Website/Personal_Website/client.tar.gz

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download package
        uses: actions/download-artifact@v3
        with:
          name: package

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{secrets.API_KEY}}
          known_hosts: unnecessary

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{secrets.API_HOST}}  >> ~/.ssh/known_hosts

      - name: Transfer build artifacts to DO Droplet
        uses: appleboy/scp-action@master
        with:
          host: ${{secrets.API_HOST}}
          username: ${{secrets.API_USERNAME}}
          key: ${{secrets.API_KEY}}
          source: client.tar.gz
          target: /var/www/temp/
      
      - name: Deploy application
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.API_HOST}}
          username:  ${{secrets.API_USERNAME}}
          key: ${{secrets.API_KEY}}
          script: |
            rm -rf /var/www/chess.parker-stovall.com/html
            mkdir /var/www/chess.parker-stovall.com/html        
            cd /var/www/temp/
            tar -xvf client.tar.gz -C /var/www/chess.parker-stovall.com/html
            cd /var/www/chess.parker-stovall.com/html
            mv client/build/* .
            rm -rf client
            rm -rf node_modules
            npm install
            npm run build
            cd /var/www/temp/
            rm -rf client.tar.gz
